FROM alpine:3.19

LABEL org.opencontainers.image.source=https://github.com/luhengsw/qd

ENV PYCURL_SSL_LIBRARY=openssl
ENV SSL_VERSION=3.1.5
ENV CURL_VERSION=8.6.0

RUN apk add --no-cache bash
SHELL ["/bin/bash", "-c"]

RUN apk add --update --no-cache git tzdata ca-certificates python3 py3-six && \
    apk add --update --no-cache --virtual .build_deps \
        wget cmake make perl autoconf g++ automake linux-headers libtool util-linux file \
        libidn2-dev libgsasl-dev krb5-dev zstd-dev nghttp2-dev zlib-dev brotli-dev \
        python3-dev py3-pip py3-setuptools py3-wheel c-ares-dev nghttp3-dev libpsl-dev && \
    file /bin/busybox && \
    [[ $(getconf LONG_BIT) = "64" && -z $(file /bin/busybox | grep -i "arm") ]] && libdir="lib64" || libdir="lib" && \
    [[ $(getconf LONG_BIT) = "32" && -z $(file /bin/busybox | grep -i "arm") ]] && configtmp="setarch i386 ./config -m32" || configtmp="./config " && \
    wget https://curl.haxx.se/download/curl-${CURL_VERSION}.tar.bz2 && \
    tar xjf curl-${CURL_VERSION}.tar.bz2 && \
    rm curl-${CURL_VERSION}.tar.bz2 && \
    git clone --depth 1 -b openssl-${SSL_VERSION}+quic https://github.com/quictls/openssl && \
    git clone --depth 1 https://github.com/ngtcp2/ngtcp2 && \
    cd openssl && \
    $configtmp enable-tls1_3 --prefix=/usr && \
    make -j$(nproc) && \
    make install_sw && \
    cd .. && rm -rf openssl && \
    cd ngtcp2 && \
    git submodule update --init && \
    autoreconf -fi && \
    ./configure PKG_CONFIG_PATH=/usr/${libdir}/pkgconfig LDFLAGS="-Wl,-rpath,/usr/${libdir}" \
        --prefix=/usr --enable-lib-only && \
    make -j$(nproc) && make install && \
    cd .. && rm -rf ngtcp2 && \
    cd curl-${CURL_VERSION} && \
    autoreconf -fi && \
    LDFLAGS="-Wl,-rpath,/usr/${libdir}" ./configure \
        --with-openssl=/usr \
        --with-nghttp2=/usr \
        --with-nghttp3=/usr \
        --with-ngtcp2=/usr \
        --prefix=/usr \
        --enable-ipv6 \
        --enable-unix-sockets \
        --with-libidn2 \
        --disable-static \
        --disable-ldap \
        --with-pic \
        --with-gssapi \
        --enable-ares && \
    make -j$(nproc) && make install && \
    cd .. && rm -rf curl-${CURL_VERSION} && \
    [[ -n $(find /usr/lib64 -name "libssl.so.*" 2>/dev/null) ]] && \
        ln -sf /usr/lib64/libssl.so.81.3 /usr/lib/ && \
        ln -sf /usr/lib64/libcrypto.so.81.3 /usr/lib/ || true && \
    pip install --no-cache-dir --compile --break-system-packages pycurl && \
    apk del .build_deps && \
    apk add --no-cache libidn2 libgsasl zlib c-ares nghttp2 nghttp3 libpsl && \
    rm -rf /var/cache/apk/* /usr/share/man/*
