FROM a76yyyy/pycurl:ja3-latest

LABEL org.opencontainers.image.source=https://github.com/luhengsw/qd

WORKDIR /usr/src/app
COPY . .

RUN apk add --no-cache \
        py3-markupsafe py3-pycryptodome py3-tornado py3-wrapt \
        py3-packaging py3-greenlet py3-urllib3 py3-cryptography \
        py3-aiosignal py3-async-timeout py3-attrs py3-frozenlist \
        py3-multidict py3-charset-normalizer py3-aiohttp \
        py3-typing-extensions py3-yarl py3-cffi && \
    { [ "$(getconf LONG_BIT)" = "32" ] && \
        echo "32-bit: skipping opencv/numpy/pillow" || \
        apk add --no-cache py3-opencv py3-pillow; } && \
    apk add --no-cache --virtual .build_deps \
        cmake make perl autoconf g++ automake \
        linux-headers libtool util-linux \
        py3-pip py3-setuptools py3-wheel python3-dev py3-numpy-dev && \
    sed -i '/pycurl/d' requirements.txt && \
    sed -i '/ddddocr/d' requirements.txt && \
    sed -i '/packaging/d' requirements.txt && \
    sed -i '/wrapt/d' requirements.txt && \
    sed -i '/pycryptodome/d' requirements.txt && \
    sed -i '/tornado/d' requirements.txt && \
    sed -i '/MarkupSafe/d' requirements.txt && \
    sed -i '/pillow/d' requirements.txt && \
    sed -i '/opencv/d' requirements.txt && \
    sed -i '/numpy/d' requirements.txt && \
    sed -i '/greenlet/d' requirements.txt && \
    sed -i '/urllib3/d' requirements.txt && \
    sed -i '/cryptography/d' requirements.txt && \
    sed -i '/aiosignal/d' requirements.txt && \
    sed -i '/async-timeout/d' requirements.txt && \
    sed -i '/attrs/d' requirements.txt && \
    sed -i '/frozenlist/d' requirements.txt && \
    sed -i '/multidict/d' requirements.txt && \
    sed -i '/charset-normalizer/d' requirements.txt && \
    sed -i '/aiohttp/d' requirements.txt && \
    sed -i '/typing-extensions/d' requirements.txt && \
    sed -i '/yarl/d' requirements.txt && \
    sed -i '/cffi/d' requirements.txt && \
    pip install --no-cache-dir -r requirements.txt --break-system-packages && \
    apk del .build_deps && \
    chmod +x /usr/src/app/update.sh && \
    ln -s /usr/src/app/update.sh /bin/update && \
    rm -rf /var/cache/apk/* /usr/share/man/*

ENV PORT=80
EXPOSE $PORT/tcp
ENV TZ=UTC

VOLUME ["/usr/src/app/config"]

CMD ["python3", "/usr/src/app/run.py"]
